### ISSUE TITLE
Control the properties of the generators via OSC

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#225] opened 2020-11-12 22:20 UTC
Acceptance criteria:

- Have each parameters of the generator accessible via OSC
- For each parameter, the OSC address is of the form "/autonomX/[generator_name]/[parameter_name] [value]
- Use the same port for the "input" messages and the "control" messages
- Use a coherent naming system for OSC messages. See spike #226 

Technical details:

- ...
- ...

**Comment by aalex** [comment] 2021-08-18 16:06
Duplicate of #31

**Closed as completed by aalex** 2021-08-18 16:06 UTC
Labels: duplicate, user story
