### ISSUE TITLE
Draw the contents of a generator using OpenGL

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#75] opened 2020-06-24 15:43 UTC
Draw the contents of a generator.

Details:

- In the backend: get the shader created in the frontend and adapt it

**Comment by simondemeule** [comment] 2020-07-22 21:48
A quick update on this: `QDeclarativeImageProvider` is deprecated as of Qt 5.6. The modern alternative is `QQuickImageProvider`. I've implemented a `GeneratorImageProvider` class as of 06ed04b. The way things works, QML will only load the image once at the time it is requested, and there doesn't seem to be a way to force it to update it without changing the source attribute. This could be worked around by alternating between two versions of the image, but that's frankly super clunky. [This thread](https://forum.qt.io/topic/105754/sending-opencv-images-continuously-from-c-to-qml/18) suggests that image providers aren't the right solution to this problem, and that video streams might be better suited for this.

**Comment by lucidism** [comment] 2020-07-23 01:06
seems like prefixing the generator ID with any string bypasses the IP auto-formatting:
![Screenshot_19](https://user-images.githubusercontent.com/34627009/88243678-2c92d080-cc5f-11ea-8e92-d096db25c056.png)

still trying to figure out how to properly hook it to the image provider :-)

**Comment by simondemeule** [comment] 2020-07-23 01:08
@lucidism thanks for the insight!

**Comment by simondemeule** [comment] 2020-07-23 01:15
@luci this is now fixed in f265a58

**Comment by lucidism** [comment] 2020-07-23 02:17
also, about the double render, this has to do with `StackLayout` manages item display (ie. no offloading, whoops!)
in that regard, `StackView` would probably be more appropriate since it seems to function more closely to a push/pop stack, like `window.History` in JS, so we should definitely consider exploring this avenue

**Comment by simondemeule** [comment] 2020-07-23 03:17
@lucidism reading the `StackLayout` documentation, it seems like only one of the elements it contains is visible at a time, which is the behaviour we want. I've confirmed that the `visible` property of `LatticeView` is properly updated using this tiny code snippet: `onVisibleChanged: {console.log("visible changed: " + visible);}`. It seems like maybe Qt is just trying to optimize loading times by pre-loading the images before it even becomes visible?

Either way it looks like the image provider solution isn't the right way to go. I'll dig into video streams ([another relevant thread here](https://forum.qt.io/topic/25669/qml-optimal-way-to-stream-update-images-qt-5)), but I'll also consider implementing a custom QtQuick object. That way memory use can be really optimized, and we can use hardware acceleration to draw things quickly. If this works this would also give us some code to derive an optimized history graph UI element from.

**Comment by simondemeule** [comment] 2020-07-23 19:54
Good news! I got a custom `QQuickItem` to render using OpenGL code defined in C++ using `QQuickFramebufferObject`. This embeds arbitrary OpenGL code as a QML item, with all the usual anchoring / alignment functions. This means we will not only be able to draw the lattice efficiently, but also rewrite the history graph in a very efficient way.

**Closed** 2020-08-05 19:07 UTC
Labels: C++, Ready
