### ISSUE TITLE
Editing a generator's name through the Rack View doesn't update its value in the list of generators

### ISSUE THREAD

**Issue by lucidism** [Xmodal/autonomX#158] opened 2020-07-24 18:18 UTC
**To Reproduce**
1. Locate the "Name" field in the GEN rack.
2. Change the value for anything else.
3. Press Enter or click outside of the field area to defocus the field and trigger the `valueChanged` signal.
4. The generator list name is not updated.

**Expected behavior**
The generator list name should reflect the updated value in the associated field, in the GEN rack.

**Screenshots**
![Screenshot_12](https://user-images.githubusercontent.com/34627009/88421335-688c7980-cdb6-11ea-8938-135cc9fd65f1.png)

**Comment by lucidism** [comment] 2020-08-09 17:05
@simondemeule I think I might've found the cause for this issue: it seems like the `GeneratorFacade::valueChangedFromAlias` signal doesn't trigger for value changes made from the GUI. for some reason which I haven't been able to find, when `GeneratorFacade::updateValueFromAlias` runs, `this->value(key)` is already equal to the incoming `value` method argument, even though the corresponding write function from `Generator` is effectively run beforehand; and so, the condition at line 83 of `GeneratorFacade.cpp` fails because both current and new values are already the same, thus preventing `GeneratorModel::dataChanged` from ever getting fired in this specific edge case.

as I've said, I'm not sure exactly what's causing this or why, and I feel like you would have a better idea of what's going on here anyway, but I do think this is a good lead.

**Comment by simondemeule** [comment] 2020-08-12 16:44
@lucidism what happens with the `GeneratorFacade` is a bit counterintuitive — this is actually the expected behaviour. 

Changes between `GeneratorFacade` and `Generator` have to be able to propagate both ways — meaning either can change and lead the other to sync with it. Changes from `GeneratorFacade` propagate to `Generator` (QML to backend) using a connection from `GeneratorFacade::valueChanged` to `Generator::updateValue`. Changes from `Generator` propagate to `GeneratorFacade` (backend to QML) using a connection from `Generator::valueChanged` to `GeneratorFacade::updateValueFromAlias`. 

The thing is, whenever a change is successfully propagated from the frontend to the backend (a QML event causes a `GeneratorFacade::valueChanged` signal to be emitted, reaching the `Generator::updateValue` slot), the appropriate QProperty setter in `Generator` will be called, which will emit a `Generator::valueChanged` signal. This in turns will cause the `GeneratorFacade::updateValueFromAlias` slot to be called. This is what you were observing — and it does not trigger a value change because the property already has been set to the desired value in the part of `QQmlPropertyMap` that takes care of emitting `GeneratorFacade::valueChanged`, meaning the condition check at line 83 fails.

I've done some more testing, and having multiple generators revealed that the `GeneratorFacade` works as expected in the racks, but only does not in the generators list. My guess is that this is either an issue with `GeneratorModel` or the QML side of the model. I'll do some bore debugging today.

**Comment by simondemeule** [comment] 2020-08-12 17:10
@lucidism this is now fixed as of d3b2285 in branch `feature/add-delete-generator-gui`. `GeneratorModel` only had connections to relay changes coming from the backend — frontend changes were omitted.

**Closed** 2020-08-18 22:34 UTC
Labels: C++, bug
